version: '3.8'
services:
  pollify-redis:
    image: redis:7-alpine
    container_name: pollify-redis
    restart: unless-stopped
  pollify-mongo: 
    image: mongo:latest
    container_name: pollify-mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:  
      - ./mongo-data:/data/db
  pollify-api: 
    container_name: pollify-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pollify-mongo
    restart: always
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
